---
title: "436 Final Project"
author: "John Quam"
date: "2023-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(sf)
library(maps)
```


### Load in the Data


```{r}
#read in the trade data
ustrade = read.csv("https://github.com/jquam15/436_Final_Project/raw/main/ustrade.csv") %>%
  rename("Deficit"="Deficit.Surplus")
#inspect the data
head(ustrade)
```


```{r}
#load in the world map with latitude and longitude coordinates from the "maps" package---this allows us to plot the outline of countries
world_map = map_data("world")
```




```{r}
#this is a function that takes a year (selected by the user) and returns a map of total trade for the US for each country in 
#the world that they traded with
merge_data = function(year) {
  #filter the ustrade dataset to only take the year the user selected
  ustrade = ustrade %>%
    filter(Year == year) %>%
    #create a new column called TotalTrade that is the sum of imports and exports
    mutate(TotalTrade = Imports + Exports)
  
  #merge this world map with our trade data so that we can fill countries by how much total trade they have
  world_map %>%
    #merge the two datasets by their appropriate column name---take all rows in the world map dataset (left join) as we need all of them to make the world map (even if the US didn't trade with that country we still need that country to create the map)
    merge(ustrade, by.x = "region", by.y = "Country", all.x = T) %>%
    #arrange the data accordingly
    arrange(group, order) %>%
    #make the plot with the countries filled in by how much they traded
    ggplot(aes(x = long, y = lat, group = group, fill = log10(TotalTrade))) +  #take a logarithmic scale so we can differentiate between countries
      geom_polygon() #plot the polygons
}

merge_data(2020)
```


```{r}
filtered_us = ustrade %>%
  filter(Year == 2020)

test = world_map %>%
    #merge the two datasets by their appropriate column name---take all rows in the world map dataset (left join) as we need all of them to make the world map (even if the US didn't trade with that country we still need that country to create the map)
    merge(filtered_us, by.x = "region", by.y = "Country", all.x = T) %>%
    #arrange the data accordingly
    arrange(group, order) %>%
    select(-subregion)


```

```{r}
#take only cases where they didn't match up
mismatch = test[!complete.cases(test), ]
#get list of countries that are in the world map BUT ARE NOT IN THE USTRADE data
world_countries = unique(mismatch$region)
#get list of ALL countries in the US trade data
trade_countries = unique(ustrade$Country)
```

```{r}
world_countries
```

```{r}
trade_countries
```




### Helper Functions 

```{r}

```



### UI

```{r}
# #get a list of continents
# continents = unique(ustrade$Continent)
# 
# ui = fluidPage(
#   selectInput("continent", "Select a Continent: ", continents, multiple=F),
#   sliderInput("years", "Select a Year Range: ", 1995, 2020, c(1995, 2020), sep=""),
#   plotOutput("lineplot"),
#   dataTableOutput("table")
# )
```

### Server





```{r}
# server = function(input, output) {
#   dataInput = reactive({
#     ustrade %>%
#       filter(  (Year >= input$years[1]) & (Year <= input$years[2]) & (Continent == input$continent) )
#   })
#   
#   output$plotOutput = renderPlot({
#       
#   })
#   
#   output$table = renderDataTable({
#     dataInput()
#   })
# }
```


```{r}
# shinyApp(ui, server)
```


























